// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-yYgoJw063CIJ6UaWm-kaCjaJLvYXfHI',
    appId: '1:982536030866:web:d542690e7627add0b3b44b',
    messagingSenderId: '982536030866',
    projectId: 'profit-compare',
    authDomain: 'profit-compare.firebaseapp.com',
    storageBucket: 'profit-compare.firebasestorage.app',
    measurementId: 'G-7JSCFKLSJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjW6Y3fEd5G7vKF9AmNxqoD6xQX20-74I',
    appId: '1:982536030866:android:572d8fdb9f11d4ceb3b44b',
    messagingSenderId: '982536030866',
    projectId: 'profit-compare',
    storageBucket: 'profit-compare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsLFUlxWf88JG7Z_NF7sR2qLHFyLzmI9E',
    appId: '1:982536030866:ios:9fd36bf78e782049b3b44b',
    messagingSenderId: '982536030866',
    projectId: 'profit-compare',
    storageBucket: 'profit-compare.firebasestorage.app',
    iosBundleId: 'com.example.profitcompare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsLFUlxWf88JG7Z_NF7sR2qLHFyLzmI9E',
    appId: '1:982536030866:ios:9fd36bf78e782049b3b44b',
    messagingSenderId: '982536030866',
    projectId: 'profit-compare',
    storageBucket: 'profit-compare.firebasestorage.app',
    iosBundleId: 'com.example.profitcompare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-yYgoJw063CIJ6UaWm-kaCjaJLvYXfHI',
    appId: '1:982536030866:web:86953832d91e6a44b3b44b',
    messagingSenderId: '982536030866',
    projectId: 'profit-compare',
    authDomain: 'profit-compare.firebaseapp.com',
    storageBucket: 'profit-compare.firebasestorage.app',
    measurementId: 'G-632FZN8L4D',
  );
}
